### ISSUE TITLE
Cocoapods please!

### ISSUE THREAD

**Issue by lfarah** [imex94/NetworkKit#1]
I'd be cool to also add Cocoapods support. I done this implementation myself last week for my library. Just follow [this post](https://guides.cocoapods.org/making/making-a-cocoapod.html) and [this checklist](https://github.com/thellimist/EZPods).
Lemme know if you need any help! :smile:

**Comment by Said-Re** [comment]
Yes I agree! And also there should be a cocoapods support for AuthFramework (I guess it already exists but it should be in the README file). If you want to make it to run you have to build the framework with the files and that's not confortable.

**Comment by imex94** [comment]
Thanks for the suggestion. Fair point. It will be available through Cocoapods soon.

**Comment by lfarah** [comment]
:smile:

**Comment by imex94** [comment]
Sorry for the slow process, Cocoapods support has been now added. http://cocoapods.org/pods/NetworkKit
